config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :posts do
    member do
      get :toggle_like
    end
  end
  resources :comments


end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader # 이미지 첨부를 위해 이 부분 추가
  
  belongs_to :user, optional: true

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy


  def self.generate_posts
    20.times do |i|
      Post.create(title: "#{i}번째 제목", content: "#{i}번째 게시글입니다.", 
        user: User.first, 
        image: File.open(("#{Rails.root}/public/image/test#{(i%6)+1}.jpg")))
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authenticate_user!
  before_action :load_object, except: [:index, :new, :create]

  def index
    if params[:type]&.to_sym == :owns # 내가 쓴 게시글
      @posts = Post.where(user: current_user)
    elsif params[:type]&.to_sym == :likes # 내가 좋아하는 게시글
      @posts = Post.where(id: current_user.likes.map(&:post_id))
    elsif params[:type]&.to_sym == :comments
      @posts = Post.where(id: current_user.comments.map(&:post_id))
    else
      @posts = Post.ransack(params[:q]).result # 모든 게시글 or 검색내용
    end
    @posts = @posts.order(updated_at: :desc).page(params[:page]).per(4)
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.create posts_params
    redirect_to posts_path, notice: "게시글을 성공적으로 등록하였습니다."
  end

  def show
    @comments = @post.comments.page(params[:page]).per(3)
    @like = @post.likes.find_by(user: current_user)
  end

  def edit;end

  def update
    @post.update posts_params
    redirect_to posts_path, notice: "게시글을 성공적으로 수정하였습니다."
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: "게시글을 성공적으로 삭제하였습니다."
  end

  def toggle_like
    @like = @post.likes.find_or_initialize_by(user: current_user)
    @like.new_record? ? @like.save : @like.destroy
    redirect_to @post, notice: "#{@like.destroyed? ? "좋아요를 취소했습니다." : "좋아요를 눌렀습니다."}"
  end

  private
  
  def posts_params
    params.require(:post).permit(:title, :content, :user_id, :image)
  end

  def load_object
    @post = Post.find_by(id: params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container my-5">
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control", placeholder: "제목" %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control", placeholder: "내용" %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <%= f.hidden_field :user_id, value: current_user&.id %>
    <%= f.submit "#{f.object.new_record? ? '등록' : '수정'}", class: "float-right" %>
  <% end %>
</div>

app/views/posts/_post_index.html.erb
<hr/>
<div class="container my-5">
  <div class = "row mb-5 justify-content-end">
    <%= form_tag request.parameters, method: :get do %>
        <div class="form-inline">
          <%= text_field_tag "q[title_or_content_i_cont]", "", class: "form-control mr-1" %>
          <%= submit_tag "검색", class: "btn btn-primary mr-1" %>
        </div>
    <% end %>
  </div>
  <div class="row">
    <% posts.each do |post| %>
      <div class="col-md-3 mb-4">
        <div class="card h-100">
          <img src="<%= post.image.url(:thumb) if post.image? %>" class="card-img-top" />
          <div class="card-body h-50">
            <h4 class="card-title"><%= post.title.truncate(10) %></h4>
            <span class="card-text"><%= post.content.truncate(50) %></span>
          </div>
          <hr/>
          <div class="mb-2">
            <% if post.user.nil? %>
              <div class="card-subtitle text-right mr-2">(탈퇴 회원)</div>
            <% else %>
              <div class="card-subtitle text-right mr-2">작성자: <%= post.user&.name %></div>
            <% end %>
          </div>
          <div class="card-footer">
            <%= link_to "자세히 보기", post_path(post&.id), class: "btn btn-outline-warning btn-sm" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <%= paginate @posts %>
  </div>
</div> 

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% if params[:type]&.to_sym == :owns %>
  <div class ="my-5">
    <h2 style= "text-align: center"> 나의 게시글 </h2>
    <%= render 'post_index', posts: @posts %>
  </div>
<% elsif params[:type]&.to_sym == :likes %>
  <div class ="my-5">
    <h2 style= "text-align: center"> 내가 좋아하는 게시글 </h2>
    <%= render "post_index", posts: @posts %>
  </div>
<% else %>
  <div class ="my-5">
    <h2 style= "text-align: center"> 전체 게시글 </h2>
    <%= render 'post_index', posts: @posts %>
  </div>
<% end %>

app/views/posts/my_comments.html.erb
<div class ="my-5">
  <h2 style= "text-align: center"> 내가 댓글 단 게시글 </h2>
  <%= render "post_index", posts: @posts %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-12">
      <img class="w-100 card-img-top" src="<%= @post.image %>" width="100%" height="500">
      <div class="card">
        <div class="card-body">
          <h4><%= @post.title %></h4>
          <hr class="my-3">
          <div class="post-body">
            <p><%= @post.content %></p>
          </div>
          <div class="mt-12">
            <% if @like %>
              <%= link_to toggle_like_post_path(@post.id) do %>
                <%= fa_icon "thumbs-up", style: "font-size:30px;" %>
              <% end %>
            <% else %>
              <%= link_to toggle_like_post_path(@post.id) do %>
                 <%= fa_icon "thumbs-down", class: "mt-2" ,style: "font-size:30px;" %>
              <% end %>
            <% end %>
          </div>
          <div class="mt-4 float-right">
            <% if current_user == @post.user %>
              <%= link_to "삭제", post_path(@post), method: :delete, data: { confirm: "게시글을 삭제하시겠습니까?" }, class: "btn btn-outline-danger" %>
              <%= link_to "수정", edit_post_path(@post), class: "btn btn-outline-secondary" %>
            <% end %>
          </div>
          <hr/>
          <h5 class="mt-5 mb-8">댓글</h5>
          <hr/>
          <%= render 'comments/form' %>
        </div>
      </div>
      <% @comments.each do |comment| %>
        <%= render "comments/comment", comment: comment %>
      <% end %>
      <div class="pagination justify-content-center mt-3">
        <%= paginate @comments %>
      </div>
    </div>
  </div>
</div>